### PR TITLE
Setup GitHub Action for CI #6

### PR DESCRIPTION
**Pull request by Bunny77K9**
Create a workflow on Node.js which runs on the latest ubuntu server in Node.js.yml.

### CODE REVIEW

**Comment by Bunny77K9** [comment]
I have also updated the environment.prod.ts file with firebase auth. Because I found some errors with it and after the updating error resolved. But still having a problem with Node.v14 action about opening chrome.

**Review by Shehanka — APPROVED** [review]
thanks for the contribution

**Comment by Shehanka** [comment]
@Bunny77K9 give us your email address. We'll send you the gift

**Comment by Bunny77K9** [comment]
wow!🎉 nadundias321@gmail.com

**Pull request merged**
